### ISSUE TITLE
LRU cache for queried items

### ISSUE THREAD

**Issue by pemontto** [nsherron90/logstash-filter-greynoise#1]
Filter looks awesome 🤘, any possibility of adding an LRU cache similar to the Logstash DNS filter and other plugins?

https://github.com/logstash-plugins/logstash-filter-dns/blob/master/lib/logstash/filters/dns.rb

**Comment by nicksherron** [comment]
Hey, thanks for the feedback! Just added the LRU cache plus IP validation and pushed it to 0.1.6. Let me know if you have any problems with it or suggestions. I didn't get to test it as much as I maybe ought to have. 🤞
